CLUSTERS = {
  "metals": [
    { "name": "Aluminum Mill Shapes", "id": "WPU102501" },
    { "name": "Copper and Brass Mill Shapes", "id": "WPU102502" },
    { "name": "Iron and Steel Scrap", "id": "WPU1012" },
    { "name": "Stainless and Alloy Steel Scrap", "id": "WPU101212" },
    { "name": "Steel Mill Products", "id": "WPU1017" },
    { "name": "Steel Pipe and Tube", "id": "WPU101706" },
    { "name": "Fabricated Steel Plate", "id": "WPU1076" },
    { "name": "Fabricated Structural Metal", "id": "WPU107405" },
    { "name": "Prefabricated Metal Buildings", "id": "WPU1079" },
    { "name": "Ornamental and Architectural Metal Work", "id": "WPU107408" },
    { "name": "Sheet Metal Products", "id": "WPU1073" },
  ],
  "concrete": [
    { "name": "Cement", "id": "WPU1322" },
    { "name": "Concrete Block and Brick", "id": "WPU1331" },
    { "name": "Concrete Contractors", "id": "PCU23811X23811X" },
    { "name": "Concrete Pipe", "id": "WPU1332" },
    { "name": "Concrete Products", "id": "WPU133" },
    { "name": "Precast Concrete Products", "id": "WPU1334" },
    { "name": "Prestressed Concrete Products", "id": "WPU1335" },
    { "name": "Ready Mixed Concrete", "id": "WPU1333" },
  ],
  "asphalt": [
    { "name": "Asphalt (At Refinery)", "id": "WPU058102" },
    { "name": "Asphalt Felts and Coatings", "id": "WPU136" },
    { "name": "Paving Mixtures", "id": "WPU1394" },
    { "name": "Prepared Asphalt and Tar Rooging and Siding Products", "id": "WPU1361" },
  ],
  "structures": [
    { "name": "Commercial Structures", "id": "WPUIP231211" },
    { "name": "Industrial Structures", "id": "WPUIP231220" },
    { "name": "Healthcare Structures", "id": "WPUIP231212" },
    { "name": "Education and Vocational Structures", "id": "WPUIP231233" },
    { "name": "New Residential Construction", "id": "WPUIP231100" },
    { "name": "New Nonresidential Building Construction", "id": "WPU801" },
    { "name": "New School Building Construction", "id": "WPU801102" },
    { "name": "New Office Building Construction", "id": "WPU801103" },
    { "name": "New Warehouse Building Construction", "id": "WPU801101" },
  ],
}
